### ISSUE TITLE
ImportError in quantum symmetry library

### ISSUE THREAD

**Issue by marinaristol** [dariopicozzi/quantumsymmetry#1]
I found the following `ImportError` when trying to import the quantum symmetry library:
 
```
/usr/local/lib/python3.10/dist-packages/quantumsymmetry/core.py in <module>
      3 from pyscf import gto, scf, symm, ao2mo, mp, mcscf
      4 from openfermion import QubitOperator, FermionOperator, jordan_wigner, utils, linalg
----> 5 from qiskit import opflow, quantum_info
      6 from qiskit_nature.operators.second_quantization import FermionicOp
      7 from qiskit_nature.converters.second_quantization import QubitConverter
 
ImportError: cannot import name 'opflow' from 'qiskit' (/usr/local/lib/python3.10/dist-packages/qiskit/__init__.py)
```
 
I am running the code in Google Colab with the following package versions:

- `qiskit == 1.2.0`
- `qiskit_nature == 0.7.2`
- `pyscf == 2.6.2`
- `Python version == 3.10.12`

It seems the error is occurring because the version of Qiskit still includes opflow, which has been deprecated in more recent versions of Qiskit. As a temporary solution, I followed the [Qiskit opflow migration guide](https://docs.quantum.ibm.com/migration-guides/qiskit-opflow-module) to update the main library files (core.py and qiskit_converter.py). I am attaching the migrated files to this issue in [quantum_symmetry_migrated.zip](https://github.com/user-attachments/files/16670517/quantum_symmetry_migrated.zip).
 
However, in the newer version of quantumsymmetry (0.2.0), an opflow import has also been added to the `encoding.py` file, causing the same error:

```
<ipython-input-2-c76831f87113> in <cell line: 14>()
---> 14 import quantumsymmetry as qs

/usr/local/lib/python3.10/dist-packages/quantumsymmetry/encoding.py in <module>
      7 from IPython.display import display, HTML
      8 from openfermion import QubitOperator, FermionOperator, jordan_wigner, utils, linalg
----> 9 from qiskit import opflow, quantum_info
     10 from qiskit_nature.operators.second_quantization import FermionicOp
     11 from qiskit_nature.converters.second_quantization import QubitConverter

ImportError: cannot import name 'opflow' from 'qiskit' (/usr/local/lib/python3.10/dist-packages/qiskit/__init__.py)

```
 
Is there any way the code in the pip package can be updated to work with Qiskit versions > 1.0?
Thank you very much for your time and assistance!

**Comment by dariopicozzi** [comment]
Hi Marina,

The latest release of QuantumSymmetry (currently version 0.2.10) is compatible with Qiskit 1.1 (and Qiskit 1.2.0), and updating QuantumSymmetry should resolve your issue.

For example, Qiskit qubit operator objects are now implemented as SparsePauliOp objects (they were previously PauliSumOp objects), a new QubitMapper object has been introduced to allow for VQE runs, and the Qiskit library imports have been updated to allow compatibility with the newer Qiskit versions.

Some broader changes beyond fixing compatibility with Qiskit include a restructuring of the package around the Encoding class, which allows to store information about the symmetry-adapted encoding in a more compact way. The behaviour of some legacy functions such as reduced_hamiltonian has been left unchanged for the sake of backward compatibility (although they are now defined as wrappers for an Encoding object).

The [QuantumSymmetry tutorials](https://colab.research.google.com/github/dariopicozzi/quantumsymmetry/blob/master/docs/tutorials/01_welcome.ipynb) have been also updated, and you’ll be able to find more complete information about the changes as well as code snippet examples on there.

I hope this helps! However, if you were to experience any further issues please do not hesitate to report them.

Best, Dario

**Comment by marinaristol** [comment]
Dear Dario, 

It is working well now! I can import it without any issues. 
Thank you so much for your time and help. I really appreciate it!

Kind regards, 
Marina
